### ISSUE TITLE
Create a "how-to" documentation in the README

### ISSUE THREAD

**Issue by hiulit** [AaronWizard/CRTScreenShader#1]
Hi,

I really like the looks of your shader, but I'm pretty new to Godot and I don't know how to apply it.
Could you explain it in the README so everyone would benefit of a "how-to" documentation?

Thanks you very much (just for taking it into account).

**Comment by AaronWizard** [comment]
I've updated the readme.
Note that since this is based on an existing shader, there are some parameters whose function I'm not quite sure of myself. I've documented the parameters that are the most important or have the most noticeable impact.

**Comment by hiulit** [comment]
Hey, thanks! I've set it up and it's working! :)

But in your example, the scene is static. I tried to get it to work in my scene, which has a camera, and the best solution I found was to:

- Create a `ParallaxBackground` node (and set its `zIndex` to `1`, so it's above everything else).
- Append a `ColorRect` child to it with its `ShaderMaterial ` set to `crt_material.tres`.

It's working, but I don't know if it's the best way to achieve that. What do you think?

Thanks!

**Comment by AaronWizard** [comment]
It's meant to be used the same way as other full screen shaders, like in Godot's official _2D Screen-Space Shaders Demo_ example.

To use the shader in a scene with a camera, you could put the _ColorRect_ that has the shader in a _CanvasLayer_.

**Comment by hiulit** [comment]
Thank you! The `CanvasLayer` did the trick!

I guess using the `CanvasLayer` would be the best way the apply the shader whether it's being used in a static scene or in one with a camera, right? If so, I think adding this info to the README would be also very valuable info for people who want to use your shader.

Thanks again. Great job!

**Comment by AaronWizard** [comment]
OK, I've both added a note about using CanvasLayers in the readme and put a CanvasLayer in the project itself.

**Comment by hiulit** [comment]
Alright! I think you can close this issue now.

I have another question, though. If my project has a size of `640x360`, the "minimum" size you talk about the `Screen Base Size` should be `360`, right?

**Comment by AaronWizard** [comment]
Yes, you would use 360 for _Screen Base Size_ if the minimum dimension of your project window size is 360. You may even set up a script that gets the project window size at runtime (not the current real window size) and assign it to the shader.

_Screen Base Size_ represents the virtual pixel size of your scene, which would be smaller (usually) than the actual pixel size of your window when your game runs. It's needed since the CRT effect applies at a smaller scale than the scene's pixels.
